[workspace]
members = [
    "hartex-discord-leader",
    "hartex-discord-utils"
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
rust-version = "1.94.0"
version = "0.17.0"

[workspace.dependencies]
git-version = "0.3.9"
rootcause = "0.11.0"
time = "0.3.44"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing = "0.1.44"
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-model = "0.17.1"

hartex-discord-utils = { path = "hartex-discord-utils" }
hartex-tracing = { path = "../rust-utilities/hartex-tracing" }

[workspace.lints.clippy]
pedantic = "deny"

[workspace.lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
