[workspace]
members = [
    "hartex-discord-leader"
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
rust-version = "1.94.0"
version = "0.18.0"

[workspace.dependencies]
rootcause = "0.11.0"
twilight-gateway = "0.17.1"
twilight-model = "0.17.1"

[workspace.lints.clippy]
pedantic = "deny"

[workspace.lints.rust]
unsafe_code = "forbid"
warnings = "deny"
