[workspace]
members = [
    "hartex-discord-actors",
    "hartex-discord-envconf",
    "hartex-discord-grpc",
    "hartex-discord-manager",
    "hartex-discord-utils",
    "hartex-discord-worker"
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
rust-version = "1.94.0"
version = "0.17.0"

[workspace.dependencies]
clap = { version = "4.5.54", features = ["color", "derive", "suggestions"] }
color-eyre = "0.6.5"
config = { version = "0.15.19", default-features = false }
dashmap = "7.0.0-rc2"
futures = "0.3.31"
kameo = { version = "0.19.2", features = ["tracing"] }
mimalloc = "0.1.48"
prost = "0.14.1"
rustls = "0.23.35"
serde = { version = "1.0.228", features = ["derive"] }
time = "0.3.44"
tokio = { version = "1.49.0", features = ["macros", "rt", "rt-multi-thread", "signal"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"
tonic-prost-build = "0.14.2"
tracing = "0.1.44"
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-model = "0.17.1"

hartex-discord-actors = { path = "hartex-discord-actors" }
hartex-discord-envconf = { path = "hartex-discord-envconf" }
hartex-discord-grpc = { path = "hartex-discord-grpc" }
hartex-discord-utils = { path = "hartex-discord-utils" }
hartex-termios-utils = { path = "../rust-utilities/hartex-termios-utils" }
hartex-tracing = { path = "../rust-utilities/hartex-tracing" }
hartex-version = { path = "../rust-utilities/hartex-version" }

[workspace.lints.clippy]
allow_attributes_without_reason = "deny"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
pedantic = { level = "deny", priority = -1 }
struct_field_names = "allow"

[workspace.lints.rust]
unfulfilled_lint_expectations = "forbid"
unsafe_code = "forbid"
warnings = "deny"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
