[package]
name = "hartex_localization_embedded"
version = "0.16.0"
edition = "2024"
description = """
Localization bindings for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.92.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i18n-embed = { version = "0.16.0", features = ["fluent-system"] }
rust-embed = "8.8.0"

[features]
