[workspace]
members = [
    "hartex-async-lazy",
    "hartex-bitflags-utils",
    "hartex-errors",
    "hartex-macro-utils",
    "hartex-tracing",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
rust-version = "1.94.0"
version = "0.17.0"

[workspace.dependencies]
rootcause = "0.11.0"
tracing-core = "0.1.36"
tracing-subscriber = { version = "0.3.22", features = ["registry", "time"] }

[workspace.lints.clippy]
pedantic = "deny"

[workspace.lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
