[package]
name = "hartex_discord_grpc_protos"
version = "0.15.0"
edition = "2024"
description = """
GRPC protobufs for HarTex
"""
license = "AGPL-3.0-or-later"
rust-version = "1.91.0"

[dependencies]
prost = "0.14.1"
tonic = "0.14.0"
tonic-prost = "0.14.0"

[build-dependencies]
tonic-prost-build = "0.14.0"

[features]
gateway = []
