[package]
name = "hartex_discord_utils"
version = "0.15.0"
edition = "2024"
description = """
Macro utilities
"""
license = "AGPL-3.0-or-later"
rust-version = "1.89.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../../discord-frontend/hartex-discord-core", features = [
    "async-net",
    "async-runtime",
    "discord-http",
    "discord-model",
    "discord-util",
    "discord-util-builder",
] }

hartex_localization_core = { path = "../../localization/hartex-localization-core" }

async-lazy = { version = "0.1.2", features = ["nightly"] }
log = "0.4.27"
miette = "7.6.0"
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
] }
tokio-postgres = "0.7.13"
tokio-rustls = { version = "0.26.2", features = ["ring"] }
unic-langid = "0.9.6"
webpki-roots = "1.0.0"

[features]
