// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

#![deny(clippy::pedantic)]
#![deny(unsafe_code)]
#![deny(warnings)]
#[path = "../generated/api_backend.rs"]
pub mod api_backend;
#[path = "../generated/configuration.rs"]
pub mod configuration;
#[path = "../generated/discord_frontend.rs"]
pub mod discord_frontend;
pub mod tables;
pub mod result;
