[package]
name = "hartex-discord-worker"
description = """
The worker component of the bot, maintaining gateway connections and handling events.
"""
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
color-eyre = { workspace = true }
kameo = { workspace = true }
mimalloc = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
twilight-gateway = { workspace = true }
twilight-model = { workspace = true }

hartex-discord-actors = { workspace = true }
hartex-discord-envconf = { workspace = true }
hartex-discord-grpc = { workspace = true }
hartex-discord-utils = { workspace = true }
hartex-termios-utils = { workspace = true }
hartex-tracing = { workspace = true }
hartex-version = { workspace = true }

[[bin]]
name = "worker"
path = "./src/main.rs"

[lints]
workspace = true
