[package]
name = "hartex-disord-leader"
description = "The leader component of the bot, maintaining gateway connections."
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
rootcause = { workspace = true }
twilight-gateway = { workspace = true }
twilight-model = { workspace = true }

[[bin]]
name = "leader"
path = "./src/main.rs"
