[package]
name = "hartex_database_migrate"
version = "0.15.0"
edition = "2024"
description = """
Database migrations.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.89.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_log = { path = "../../rust-utilities/hartex-log" }

dotenvy = "0.15.7"
log = "0.4.27"
miette = { version = "7.6.0", features = ["fancy"] }
refinery = { version = "0.8.16", features = ["tokio-postgres"] }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.13"
