[package]
name = "hartex-discord-utils"
description = "Useful utilities for the Discord frontend."
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
color-eyre = { workspace = true }
twilight-http = { workspace = true }

[lints]
workspace = true
