/*
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * This file is part of HarTex.
 *
 * HarTex
 * Copyright (c) 2021-2026 HarTex Project Developers
 *
 * HarTex is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * HarTex is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with HarTex. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package dev.teamhartex.hartex.protobufs.manager;

message ConnectionInfoRequest {}

message ConnectionInfoResponse {
  WorkerSessionStartLimit session_start_limit = 1;
  uint32 recommended_shards = 2;
  uint64 start_timestamp = 4;
}

message IdentifyRequest {
  uint32 capacity = 1;
}

message ShardResumeData {
  string session_id = 1;
  uint64 seq = 2;
  string resume_gateway_url = 3;
}

message ShardAssignment {
  uint32 shard_id = 1;
  uint32 shard_count = 2;
  optional ShardResumeData resume_data = 3;
}

message WorkerSessionStartLimit {
  uint32 max_concurrency = 1;
  uint32 remaining = 2;
  uint64 reset_after = 3;
  uint32 total = 4;
}

message ReadyResponse {
  uint32 worker_id = 1;
  repeated ShardAssignment initial_assignments = 2;
  WorkerSessionStartLimit session_start_limit = 3;
}

message WhoamiRequest {}

message WhoamiResponse {
  string username = 1;
  string discriminator = 2;
  string user_id = 3;
}

service Manager {
  rpc ConnectionInfo(ConnectionInfoRequest) returns (ConnectionInfoResponse);

  rpc Identify(IdentifyRequest) returns (ReadyResponse);

  rpc Whoami(WhoamiRequest) returns (WhoamiResponse);
}
