services:
  api-backend:
    container_name: api-1
    build:
      dockerfile: api-backend/Dockerfile
      context: ..
    ports:
      - "3333:3333"
  proxy:
    image: twilightrs/http-proxy:metrics
    container_name: proxy-1
    environment:
      DISCORD_TOKEN: "irrelevant"
      RUST_LOG: "trace"
    ports:
      - "3000:80"
