[package]
name = "hartex-discord-manager"
description = """
The instance manager of the bot, configuring how many instances of the bot is run.
"""
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
color-eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

hartex-termios-utils = { workspace = true }
hartex-tracing = { workspace = true }

[[bin]]
name = "manager"
path = "./src/main.rs"

[lints]
workspace = true
