[package]
name = "hartex-discord-manager"
description = """
The instance manager of the bot, configuring how many instances of the bot is run.
"""
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
dashmap = { workspace = true }
rustls = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
twilight-http = { workspace = true }
twilight-model = { workspace = true }

hartex-discord-envconf = { workspace = true }
hartex-discord-grpc = { workspace = true }
hartex-termios-utils = { workspace = true }
hartex-tracing = { workspace = true }
hartex-version = { workspace = true }

[[bin]]
name = "manager"
path = "./src/main.rs"

[lints]
workspace = true
