[package]
name = "hartex_backend_driver"
version = "0.15.0"
edition = "2024"
description = """
Backend server driver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.92.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_routes = { path = "../hartex-backend-routes" }

hartex_errors = { path = "../../rust-utilities/hartex-errors" }
hartex_tracing = { path = "../../rust-utilities/hartex-tracing" }

axum = "0.8.6"
dotenvy = "0.15.7"
miette = { version = "7.6.0", features = ["fancy"] }
mimalloc = "0.1.48"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["timeout", "trace"] }
tracing = "0.1.41"
utoipa = "5.4.0"
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }

[features]
