[package]
name = "hartex_backend_driver"
version = "0.15.0"
edition = "2024"
description = """
Backend server driver
"""
license = "AGPL-3.0-or-later"
rust-version = "1.89.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_routes = { path = "../hartex-backend-routes" }

hartex_errors = { path = "../../rust-utilities/hartex-errors" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

axum = "0.8.4"
bb8-postgres = "0.9.0"
dotenvy = "0.15.7"
log = "0.4.27"
miette = { version = "7.6.0", features = ["fancy"] }
tokio = { version = "1.45.0", features = ["full"] }
tower-http = { version = "0.6.4", features = ["timeout", "trace"] }
tracing = { version = "0.1.41", features = ["log-always"] }
utoipa = "5.3.1"
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }

[features]
