// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct PluginEnabled<'a> {
    pool: &'a PgPool,
    query: Option<Query<'a, Postgres, PgArguments>>,
}
impl<'a> PluginEnabled<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub async fn bind(mut self, plugin: String, guild_id: String) -> Self {
        self.query
            .replace(
                sqlx::query(
                        "SELECT EXISTS (SELECT true FROM \"Configuration\".\"Nightly\".\"GuildConfigurations\" WHERE \"enabled_plugins\" @> ARRAY[$1] AND \"guild_id\" = $2)",
                    )
                    .bind(plugin)
                    .bind(guild_id),
            );
        self
    }
    #[must_use = "Query result(s) must be used"]
    pub async fn exists(self) -> crate::result::Result<bool> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".executor() has not been called on this query yet",
                ),
            )?
            .fetch_one(self.pool)
            .await
            .get::<bool, &str>("exists")
            .into_crate_result()
    }
}
