[package]
name = "hartex-discord-envconf"
description = """
Configurations for the bot that is only specified in environment variables.
"""
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
config = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
