[package]
name = "hartex_discord_entitycache_inmemory"
version = "0.15.0"
edition = "2024"
description = """
In-memory cache implementation for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.90.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }
hartex_discord_entitycache_entities = { path = "../hartex-discord-entitycache-entities" }

dashmap = "6.1.0"

[features]
