[package]
name = "hartex_async_lazy"
version = "0.15.0"
edition = "2024"
description = """
Macro utilities
"""
license = "AGPL-3.0-or-later"
rust-version = "1.92.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.47.1", features = ["sync"] }

[features]
