[package]
name = "bot-gateway"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
config = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
twilight-gateway = { workspace = true }
twilight-http = { workspace = true }

shared-tracing = { workspace = true }
