[package]
name = "hartex-version"
description = """
Utility to fetch the version of a build of HarTex based on various environmental
parameters.
"""
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
git-version = { workspace = true }

[build-dependencies]
time = { workspace = true }

[lints]
workspace = true
