// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct CachedEmojiUpsert {
    animated: bool,
    name: String,
    id: String,
    guild_id: String,
    managed: bool,
}
