// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct CachedUserUpsert {
    avatar: String,
    id: String,
    bot: bool,
    name: String,
    discriminator: String,
    global_name: String,
}
impl CachedUserUpsert {
    #[must_use = "Queries must be executed after construction"]
    pub fn bind(
        avatar: String,
        id: String,
        bot: bool,
        name: String,
        discriminator: String,
        global_name: String,
    ) -> Self {
        Self {
            avatar,
            id,
            bot,
            name,
            discriminator,
            global_name,
        }
    }
}
