// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct CachedMemberSelectByGuildId {
    guild_id: String,
}
impl CachedMemberSelectByGuildId {
    #[must_use = "Queries must be executed after construction"]
    pub fn bind(guild_id: String) -> Self {
        Self { guild_id }
    }
}
