// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct CachedGuildUpsert<'a> {
    pool: &'a PgPool,
    query: Option<Query<'a, Postgres, PgArguments>>,
}
impl<'a> CachedGuildUpsert<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub fn bind(
        mut self,
        default_message_notifications: i16,
        explicit_content_filter: i16,
        features: Vec<String>,
        icon: Option<String>,
        large: bool,
        name: String,
        owner_id: String,
        id: String,
        mfa_level: i16,
        premium_subscription_count: Option<i64>,
        premium_tier: i16,
        verification_level: i16,
    ) -> Self {
        self.query
            .replace(
                sqlx::query(
                        "INSERT INTO \"DiscordFrontend\".\"Nightly\".\"CachedGuilds\" (\"default_message_notifications\", \"explicit_content_filter\", \"features\", \"icon\", \"large\", \"name\", \"owner_id\", \"id\", \"mfa_level\", \"premium_subscription_count\", \"premium_tier\", \"verification_level\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) ON CONFLICT(\"id\") DO UPDATE SET \"default_message_notifications\" = $1, \"explicit_content_filter\" = $2, \"features\" = $3, \"icon\" = $4, \"large\" = $5, \"mfa_level\" = $9, \"name\" = $6, \"owner_id\" = $7, \"premium_subscription_count\" = $10, \"premium_tier\" = $11, \"verification_level\" = $12",
                    )
                    .bind(default_message_notifications)
                    .bind(explicit_content_filter)
                    .bind(features)
                    .bind(icon)
                    .bind(large)
                    .bind(name)
                    .bind(owner_id)
                    .bind(id)
                    .bind(mfa_level)
                    .bind(premium_subscription_count)
                    .bind(premium_tier)
                    .bind(verification_level),
            );
        self
    }
    pub async fn execute(self) -> crate::result::Result<()> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .execute(self.pool)
            .await
            .into_crate_result()?;
        Ok(())
    }
}
