// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct CachedMemberSelectByGuildId<'a> {
    pool: &'a PgPool,
    query: Option<
        QueryAs<
            'a,
            Postgres,
            crate::tables::discord_frontend::NightlyCachedMembers,
            PgArguments,
        >,
    >,
}
impl<'a> CachedMemberSelectByGuildId<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub fn bind(mut self, guild_id: String) -> Self {
        self.query
            .replace(
                sqlx::query_as(
                        "SELECT * FROM \"DiscordFrontend\".\"Nightly\".\"CachedMembers\" WHERE \"guild_id\" = $1",
                    )
                    .bind(guild_id),
            );
        self
    }
    pub async fn one(
        self,
    ) -> crate::result::Result<crate::tables::discord_frontend::NightlyCachedMembers> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .fetch_one(self.pool)
            .await
            .into_crate_result()
    }
    pub async fn all(
        self,
    ) -> crate::result::Result<
        Vec<crate::tables::discord_frontend::NightlyCachedMembers>,
    > {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .fetch_all(self.pool)
            .await
            .into_crate_result()
    }
}
