// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct CachedMemberSelectByUserIdAndGuildId {
    user_id: String,
    guild_id: String,
}
