// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct CachedEmojiUpsert {
    animated: bool,
    name: String,
    id: String,
    guild_id: String,
    managed: bool,
}
impl CachedEmojiUpsert {
    #[must_use = "Queries must be executed after construction"]
    pub fn bind(
        animated: bool,
        name: String,
        id: String,
        guild_id: String,
        managed: bool,
    ) -> Self {
        Self {
            animated,
            name,
            id,
            guild_id,
            managed,
        }
    }
}
