// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct CachedEmojiUpsert<'a> {
    pool: &'a PgPool,
    query: Option<Query<'a, Postgres, PgArguments>>,
}
impl<'a> CachedEmojiUpsert<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub fn bind(
        mut self,
        animated: bool,
        name: String,
        id: String,
        guild_id: String,
        managed: bool,
    ) -> Self {
        self.query
            .replace(
                sqlx::query(
                        "INSERT INTO \"DiscordFrontend\".\"Nightly\".\"CachedEmojis\" (\"animated\", \"name\", \"id\", \"guild_id\", \"managed\") VALUES ($1, $2, $3, $4, $5) ON CONFLICT(\"id\") DO UPDATE SET \"guild_id\" = $4, \"animated\" = $1, \"name\" = $2, \"managed\" = $5",
                    )
                    .bind(animated)
                    .bind(name)
                    .bind(id)
                    .bind(guild_id)
                    .bind(managed),
            );
        self
    }
    pub async fn execute(self) -> crate::result::Result<()> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .execute(self.pool)
            .await
            .into_crate_result()?;
        Ok(())
    }
}
