// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct CachedUserUpsert<'a> {
    pool: &'a PgPool,
    query: Option<Query<'a, Postgres, PgArguments>>,
}
impl<'a> CachedUserUpsert<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub async fn bind(
        mut self,
        avatar: Option<String>,
        id: String,
        bot: bool,
        name: String,
        discriminator: String,
        global_name: Option<String>,
    ) -> Self {
        self.query
            .replace(
                sqlx::query(
                        "INSERT INTO \"DiscordFrontend\".\"Nightly\".\"CachedUsers\" (\"avatar\", \"id\", \"bot\", \"name\", \"discriminator\", \"global_name\") VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT(\"id\") DO UPDATE SET \"avatar\" = $1, \"bot\" = $3, \"name\" = $4, \"discriminator\" = $5, \"global_name\" = $6",
                    )
                    .bind(avatar)
                    .bind(id)
                    .bind(bot)
                    .bind(name)
                    .bind(discriminator)
                    .bind(global_name),
            );
        self
    }
    pub async fn execute(self) -> crate::result::Result<()> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .execute(self.pool)
            .await
            .into_crate_result()?;
        Ok(())
    }
}
