// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct CachedMemberSelectByUserIdAndGuildId {
    user_id: String,
    guild_id: String,
}
impl CachedMemberSelectByUserIdAndGuildId {
    #[must_use = "Queries must be executed after construction"]
    pub fn bind(user_id: String, guild_id: String) -> Self {
        Self { user_id, guild_id }
    }
}
