// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct CachedRoleUpsert<'a> {
    pool: &'a PgPool,
    query: Option<Query<'a, Postgres, PgArguments>>,
}
impl<'a> CachedRoleUpsert<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub fn bind(
        mut self,
        color: i64,
        icon: Option<String>,
        id: String,
        guild_id: String,
        flags: i32,
        hoist: bool,
        managed: bool,
        mentionable: bool,
        position: i32,
    ) -> Self {
        self.query
            .replace(
                sqlx::query(
                        "INSERT INTO \"DiscordFrontend\".\"Nightly\".\"CachedRoles\" (\"color\", \"icon\", \"id\", \"guild_id\", \"flags\", \"hoist\", \"managed\", \"mentionable\", \"position\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT(\"id\", \"guild_id\") DO UPDATE SET \"color\" = $1, \"icon\" = $2, \"flags\" = $5, \"hoist\" = $6, \"managed\" = $7, \"mentionable\" = $8, \"position\" = $9",
                    )
                    .bind(color)
                    .bind(icon)
                    .bind(id)
                    .bind(guild_id)
                    .bind(flags)
                    .bind(hoist)
                    .bind(managed)
                    .bind(mentionable)
                    .bind(position),
            );
        self
    }
    pub async fn execute(self) -> crate::result::Result<()> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .execute(self.pool)
            .await
            .into_crate_result()?;
        Ok(())
    }
}
