// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use sqlx::Postgres;
use sqlx::postgres::PgArguments;
use sqlx::postgres::PgPool;
use sqlx::query::Query;
use sqlx::query::QueryAs;
use crate::result::IntoCrateResult;
pub struct CachedMemberUpsert<'a> {
    pool: &'a PgPool,
    query: Option<Query<'a, Postgres, PgArguments>>,
}
impl<'a> CachedMemberUpsert<'a> {
    pub fn new(pool: &'a PgPool) -> Self {
        Self { pool, query: None }
    }
    pub async fn bind(
        mut self,
        flags: i64,
        joined_at: Option<chrono::DateTime<chrono::offset::Utc>>,
        nick: Option<String>,
        user_id: String,
        guild_id: String,
        roles: Vec<String>,
    ) -> Self {
        self.query
            .replace(
                sqlx::query(
                        "INSERT INTO \"DiscordFrontend\".\"Nightly\".\"CachedMembers\" (\"flags\", \"joined_at\", \"nick\", \"user_id\", \"guild_id\", \"roles\") VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT(\"user_id\", \"guild_id\") DO UPDATE SET \"flags\" = $1, \"joined_at\" = $2, \"nick\" = $3, \"roles\" = $6",
                    )
                    .bind(flags)
                    .bind(joined_at)
                    .bind(nick)
                    .bind(user_id)
                    .bind(guild_id)
                    .bind(roles),
            );
        self
    }
    pub async fn execute(self) -> crate::result::Result<()> {
        self.query
            .ok_or(
                crate::result::Error::Generic(
                    ".bind() has not been called on this query yet",
                ),
            )?
            .execute(self.pool)
            .await
            .into_crate_result()?;
        Ok(())
    }
}
