// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use std::env;
use tokio::net::TcpStream;
use wtx::database::Executor as _;
use wtx::database::client::postgres::Executor;
use wtx::database::client::postgres::ExecutorBuffer;
use wtx::misc::Uri;
use crate::result::IntoCrateResult;
pub struct CachedMemberUpsert {
    db_executor: Option<Executor<wtx::Error, ExecutorBuffer, TcpStream>>,
    executor_constructor: for<'a> fn(Uri<&'a str>) -> crate::internal::Ret<'a>,
    flags: i64,
    joined_at: chrono::DateTime<chrono::offset::Utc>,
    nick: String,
    user_id: String,
    guild_id: String,
    roles: Vec<String>,
}
impl CachedMemberUpsert {
    #[must_use = "Queries must be executed after construction"]
    pub fn bind(
        flags: i64,
        joined_at: chrono::DateTime<chrono::offset::Utc>,
        nick: String,
        user_id: String,
        guild_id: String,
        roles: Vec<String>,
    ) -> Self {
        Self {
            db_executor: None,
            executor_constructor: crate::internal::__internal_executor_constructor
                as for<'a> fn(Uri<&'a str>) -> crate::internal::Ret<'a>,
            flags,
            joined_at,
            nick,
            user_id,
            guild_id,
            roles,
        }
    }
    pub async fn executor(mut self) -> crate::result::Result<Self> {
        self.db_executor
            .replace(
                (self
                    .executor_constructor)(
                        Uri::new(&env::var("DISCORD_FRONTEND_PGSQL_URL").unwrap()),
                    )
                    .await?,
            );
        Ok(self)
    }
    pub async fn execute(self) -> crate::result::Result<u64> {
        self.db_executor
            .ok_or(
                crate::result::Error::Generic(
                    ".executor() has not been called on this query yet",
                ),
            )?
            .execute_with_stmt(
                "INSERT INTO \"DiscordFrontend\".\"Nightly\".\"CachedMembers\" (\"flags\", \"joined_at\", \"nick\", \"user_id\", \"guild_id\", \"roles\") VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT(\"user_id\", \"guild_id\") DO UPDATE SET \"flags\" = $1, \"joined_at\" = $2, \"nick\" = $3, \"roles\" = $6",
                (
                    self.flags,
                    self.joined_at,
                    self.nick,
                    self.user_id,
                    self.guild_id,
                    self.roles,
                ),
            )
            .await
            .into_crate_result()
    }
}
