// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use wtx::database::Record as _;
use wtx::database::client::postgres::Record;
pub struct StartTimestamps {
    timestamp: chrono::DateTime<chrono::offset::Utc>,
    component: String,
}
impl StartTimestamps {
    #[must_use]
    pub fn timestamp(&self) -> chrono::DateTime<chrono::offset::Utc> {
        self.timestamp
    }
    #[must_use]
    pub fn component(&self) -> &str {
        self.component.as_str()
    }
}
impl<'exec, E: From<wtx::Error>> TryFrom<Record<'exec, E>> for StartTimestamps
where
    crate::result::Error: From<E>,
{
    type Error = crate::result::Error;
    fn try_from(record: Record<'exec, E>) -> crate::result::Result<Self> {
        Ok(Self {
            timestamp: record.decode("timestamp")?,
            component: record.decode("component")?,
        })
    }
}
