// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct StartTimestamps {
    component: String,
    timestamp: time::OffsetDateTime,
}
impl StartTimestamps {
    #[must_use]
    pub fn component(&self) -> &str {
        self.component.as_str()
    }
    #[must_use]
    pub fn timestamp(&self) -> time::OffsetDateTime {
        self.timestamp
    }
}
