// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

use wtx::database::Record as _;
use wtx::database::client::postgres::Record;
pub struct NightlyCachedEmojis {
    animated: bool,
    guild_id: String,
    id: String,
    managed: bool,
    name: String,
}
impl NightlyCachedEmojis {
    #[must_use]
    pub fn animated(&self) -> bool {
        self.animated
    }
    #[must_use]
    pub fn guild_id(&self) -> &str {
        self.guild_id.as_str()
    }
    #[must_use]
    pub fn id(&self) -> &str {
        self.id.as_str()
    }
    #[must_use]
    pub fn managed(&self) -> bool {
        self.managed
    }
    #[must_use]
    pub fn name(&self) -> &str {
        self.name.as_str()
    }
}
impl<'exec, E: From<wtx::Error>> TryFrom<Record<'exec, E>> for NightlyCachedEmojis
where
    crate::result::Error: From<E>,
{
    type Error = crate::result::Error;
    fn try_from(record: Record<'exec, E>) -> crate::result::Result<Self> {
        Ok(Self {
            animated: record.decode("animated")?,
            guild_id: record.decode("guild_id")?,
            id: record.decode("id")?,
            managed: record.decode("managed")?,
            name: record.decode("name")?,
        })
    }
}
pub struct NightlyCachedGuilds {
    default_message_notifications: i16,
    explicit_content_filter: i16,
    features: Vec<String>,
    icon: Option<String>,
    id: String,
    large: bool,
    mfa_level: i16,
    name: String,
    owner_id: String,
    premium_subscription_count: Option<i64>,
    premium_tier: i16,
    verification_level: i16,
}
impl NightlyCachedGuilds {
    #[must_use]
    pub fn default_message_notifications(&self) -> i16 {
        self.default_message_notifications
    }
    #[must_use]
    pub fn explicit_content_filter(&self) -> i16 {
        self.explicit_content_filter
    }
    #[must_use]
    pub fn features(&self) -> &[String] {
        self.features.as_slice()
    }
    #[must_use]
    pub fn icon(&self) -> Option<&str> {
        self.icon.as_deref()
    }
    #[must_use]
    pub fn id(&self) -> &str {
        self.id.as_str()
    }
    #[must_use]
    pub fn large(&self) -> bool {
        self.large
    }
    #[must_use]
    pub fn mfa_level(&self) -> i16 {
        self.mfa_level
    }
    #[must_use]
    pub fn name(&self) -> &str {
        self.name.as_str()
    }
    #[must_use]
    pub fn owner_id(&self) -> &str {
        self.owner_id.as_str()
    }
    #[must_use]
    pub fn premium_subscription_count(&self) -> Option<i64> {
        self.premium_subscription_count
    }
    #[must_use]
    pub fn premium_tier(&self) -> i16 {
        self.premium_tier
    }
    #[must_use]
    pub fn verification_level(&self) -> i16 {
        self.verification_level
    }
}
impl<'exec, E: From<wtx::Error>> TryFrom<Record<'exec, E>> for NightlyCachedGuilds
where
    crate::result::Error: From<E>,
{
    type Error = crate::result::Error;
    fn try_from(record: Record<'exec, E>) -> crate::result::Result<Self> {
        Ok(Self {
            default_message_notifications: record
                .decode("default_message_notifications")?,
            explicit_content_filter: record.decode("explicit_content_filter")?,
            features: record.decode("features")?,
            icon: record.decode_opt("icon")?,
            id: record.decode("id")?,
            large: record.decode("large")?,
            mfa_level: record.decode("mfa_level")?,
            name: record.decode("name")?,
            owner_id: record.decode("owner_id")?,
            premium_subscription_count: record.decode_opt("premium_subscription_count")?,
            premium_tier: record.decode("premium_tier")?,
            verification_level: record.decode("verification_level")?,
        })
    }
}
pub struct NightlyCachedMembers {
    flags: i64,
    guild_id: String,
    joined_at: Option<chrono::DateTime<chrono::offset::Utc>>,
    nick: Option<String>,
    roles: Vec<String>,
    user_id: String,
}
impl NightlyCachedMembers {
    #[must_use]
    pub fn flags(&self) -> i64 {
        self.flags
    }
    #[must_use]
    pub fn guild_id(&self) -> &str {
        self.guild_id.as_str()
    }
    #[must_use]
    pub fn joined_at(&self) -> Option<chrono::DateTime<chrono::offset::Utc>> {
        self.joined_at
    }
    #[must_use]
    pub fn nick(&self) -> Option<&str> {
        self.nick.as_deref()
    }
    #[must_use]
    pub fn roles(&self) -> &[String] {
        self.roles.as_slice()
    }
    #[must_use]
    pub fn user_id(&self) -> &str {
        self.user_id.as_str()
    }
}
impl<'exec, E: From<wtx::Error>> TryFrom<Record<'exec, E>> for NightlyCachedMembers
where
    crate::result::Error: From<E>,
{
    type Error = crate::result::Error;
    fn try_from(record: Record<'exec, E>) -> crate::result::Result<Self> {
        Ok(Self {
            flags: record.decode("flags")?,
            guild_id: record.decode("guild_id")?,
            joined_at: record.decode_opt("joined_at")?,
            nick: record.decode_opt("nick")?,
            roles: record.decode("roles")?,
            user_id: record.decode("user_id")?,
        })
    }
}
pub struct NightlyCachedRoles {
    color: i64,
    flags: i32,
    guild_id: String,
    hoist: bool,
    icon: Option<String>,
    id: String,
    managed: bool,
    mentionable: bool,
    position: i32,
}
impl NightlyCachedRoles {
    #[must_use]
    pub fn color(&self) -> i64 {
        self.color
    }
    #[must_use]
    pub fn flags(&self) -> i32 {
        self.flags
    }
    #[must_use]
    pub fn guild_id(&self) -> &str {
        self.guild_id.as_str()
    }
    #[must_use]
    pub fn hoist(&self) -> bool {
        self.hoist
    }
    #[must_use]
    pub fn icon(&self) -> Option<&str> {
        self.icon.as_deref()
    }
    #[must_use]
    pub fn id(&self) -> &str {
        self.id.as_str()
    }
    #[must_use]
    pub fn managed(&self) -> bool {
        self.managed
    }
    #[must_use]
    pub fn mentionable(&self) -> bool {
        self.mentionable
    }
    #[must_use]
    pub fn position(&self) -> i32 {
        self.position
    }
}
impl<'exec, E: From<wtx::Error>> TryFrom<Record<'exec, E>> for NightlyCachedRoles
where
    crate::result::Error: From<E>,
{
    type Error = crate::result::Error;
    fn try_from(record: Record<'exec, E>) -> crate::result::Result<Self> {
        Ok(Self {
            color: record.decode("color")?,
            flags: record.decode("flags")?,
            guild_id: record.decode("guild_id")?,
            hoist: record.decode("hoist")?,
            icon: record.decode_opt("icon")?,
            id: record.decode("id")?,
            managed: record.decode("managed")?,
            mentionable: record.decode("mentionable")?,
            position: record.decode("position")?,
        })
    }
}
pub struct NightlyCachedUsers {
    avatar: Option<String>,
    bot: bool,
    discriminator: String,
    global_name: Option<String>,
    id: String,
    name: String,
}
impl NightlyCachedUsers {
    #[must_use]
    pub fn avatar(&self) -> Option<&str> {
        self.avatar.as_deref()
    }
    #[must_use]
    pub fn bot(&self) -> bool {
        self.bot
    }
    #[must_use]
    pub fn discriminator(&self) -> &str {
        self.discriminator.as_str()
    }
    #[must_use]
    pub fn global_name(&self) -> Option<&str> {
        self.global_name.as_deref()
    }
    #[must_use]
    pub fn id(&self) -> &str {
        self.id.as_str()
    }
    #[must_use]
    pub fn name(&self) -> &str {
        self.name.as_str()
    }
}
impl<'exec, E: From<wtx::Error>> TryFrom<Record<'exec, E>> for NightlyCachedUsers
where
    crate::result::Error: From<E>,
{
    type Error = crate::result::Error;
    fn try_from(record: Record<'exec, E>) -> crate::result::Result<Self> {
        Ok(Self {
            avatar: record.decode_opt("avatar")?,
            bot: record.decode("bot")?,
            discriminator: record.decode("discriminator")?,
            global_name: record.decode_opt("global_name")?,
            id: record.decode("id")?,
            name: record.decode("name")?,
        })
    }
}
