// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct StartTimestampUpsert {
    component: String,
    timestamp: chrono::DateTime<chrono::offset::Utc>,
}
impl StartTimestampUpsert {
    #[must_use = "Queries must be executed after construction"]
    pub fn bind(
        component: String,
        timestamp: chrono::DateTime<chrono::offset::Utc>,
    ) -> Self {
        Self { component, timestamp }
    }
}
