// ==================! DO NOT MODIFY !==================
// This file is automatically generated by `hartex-database-typedsql`. Please do not modify this in
// any way.
// ==================! DO NOT MODIFY !==================

pub struct StartTimestampUpsert {
    component: String,
    timestamp: chrono::DateTime<chrono::offset::Utc>,
}
